### PR TITLE
desktop settings for Fluxbox

### PR DESCRIPTION
**Pull request by napcok**
@oberon2007

### CODE REVIEW

**Comment by udeved** [comment]
There are several things wrong in this pull request.
If it is supposed to be in, please coordinate @oberon2007 
https://github.com/manjaro/manjaro-tools-iso-profiles/pull/137#issuecomment-195597765

**Comment by oberon2007** [comment]
will look at it a little later! :)

**Comment by oberon2007** [comment]
Ok:
- remove **lightdm/**. That belongs in the profile and it is already there anyway :wink: 
- same for **oblogout.conf**
- **.bashrc** works differently now: Have a look at **shared/bash/.bashrc**. This one will be installed. In case you absolutely need other stuff in .bashrc this goes in your **skel/.extend.bashrc**. You will definitely have to export $BROWSER ! Have a look in i3 how I did it there!
Good job, @napcok ! :smiling_imp:

**Comment by oberon2007** [comment]
Looking good already! Two more things:
Please remove folders **.moonchild** and **.mozilla** and instead add in the package list in profile **manjaro-firefox-settings** This is our new strategy to configure the manjaro default for FF and Palemoon.
I'm afraid we cannot publish ISOs with infinality bundle pre-installed - it's a problem with copyright unfortunately... :stuck_out_tongue_closed_eyes:
Let us know how your testbuilds work out! :smiley:

**Comment by napcok** [comment]
Looks like I'm stuck trying to figure out how to configure buildiso to use my custom online repository :(

**Comment by udeved** [comment]
https://github.com/manjaro/manjaro-tools-iso-profiles/blob/master/README.md

**Comment by oberon2007** [comment]
There are already three custom repos in your profile:
https://github.com/napcok/manjaro-tools-iso-profiles/blob/master/community/fluxbox/pacman-multilib.conf#L92
You can add another one there (and as I suggested, remove the infinality one instead ... ;) )

**Comment by napcok** [comment]
@udeved , @oberon2007 thanks. Test iso building in progress...

**Comment by napcok** [comment]
Testbuild iso builds and works fine here - installed in Virtualbox. Look the same as 15.12 release.
The only missing thing I see is custom bookmarks in Palemoon. :)

**Comment by oberon2007** [comment]
Awesome! :smiley: For palemoon-settings for now you can add **manjaro-firefox-settings**. It installs manjaro defaults for both firefox and palemoon now - even though it's not completely ideal, yet. We're still working on an [issue with the icons](https://github.com/manjaro/manjaro-firefox-settings/issues/1) ... We shall see where exactly we can go with this package.
I am merging this now and will build **manjaro-fluxbox-settings** for the repo later.
Did you add any other packages in your custom repo?

**Comment by napcok** [comment]
No other packages, only **manjaro-fluxbox-settings ** was taken from my custom repo to build iso.

**Pull request merged**
