### PR TITLE
add jwm

### PR DESCRIPTION
**Pull request by oberon2007**
We're gettings there... :wink: 
Have a look please @udeved @holmeslinux

### CODE REVIEW

**Comment by oberon2007** [comment]
@holmeslinux for your information: **.bashrc** has been moved to the [shared folder](https://github.com/manjaro/desktop-settings/blob/master/shared/bash/.bashrc)
Your extras are now in **jwm/etc/skel/.extend.bashrc** which is sourced by **.bashrc**
In case I missed something we can add anything there :)

**Comment by oberon2007** [comment]
There is one question I still have @holmeslinux : **pacli** is there a reason why you don't use the package? and why is the script currently in in **skel/.managers** ?
Other than that, @udeved ? Accepted?

**Comment by holmeslinux** [comment]
@oberon2007 , although the package pacli and pacli-jwm have the same functions, the pacli-jwm the jwm has a different leiaut. you think we should a package for him? also have the jvmconf!

**Comment by oberon2007** [comment]
Yes. Lets make a **pacli-jwm** and have it conflict properly with the regular one!
What is **jvmconf**? Can it also go to **/usr/bin** does it have to be placed in **.managers** really? If **/usr/bin** is ok, we can move it to **desktop-settings/scripts**. But it can also stay where it is I guess since it is jwm-specific...

**Comment by holmeslinux** [comment]
yes you can go in the bin.
i will make the PKGBUILD.
see a picture with jwmconf and pacli: http://www.auplod.com/u/daolpu76cfb.png.

**Comment by oberon2007** [comment]
I think it's fine now. Moved pacli and jwmconf to packages.

**Pull request merged**
