### PR TITLE
Remove tmux files from bspwm settings

### PR DESCRIPTION
**Pull request by Chrysostomus**
The relevant files are provided by st-manjaro instead.

### CODE REVIEW

**Comment by oberon2007** [comment]
Could you please package the backgrounds and theme separately?

**Comment by Chrysostomus** [comment]
Yes. I think I could just depend on gnome wallpapers and package icons in a global location. Not possible to separate entire theme though, configuration will not load without it.

**Comment by oberon2007** [comment]
can it not just depend on the theme?

**Comment by Chrysostomus** [comment]
It can, but why? Why would we want to hardcode wallpaper and theming? What is there to be gained in this? With icons I understand it makes sense to share them between users, but why theme?

**Comment by oberon2007** [comment]
Not the wallpapers of course. I meant the theme because you say
> Not possible to separate entire theme though, configuration will not load without it.

**Comment by oberon2007** [comment]
What I meant to package separately is just everything in the 'cesious' folder.

**Comment by Chrysostomus** [comment]
I meant that theme.lua from cesious directory should be in users dotfiles. Everything else can be moved to a global location, but that file has stuff that should be configurable by the user.

**Comment by Chrysostomus** [comment]
Okay, done.

**Comment by Chrysostomus** [comment]
Added a package for cesious-theme in packages-community and updated the pkgbuild for manjaro-awesome-settings accordingly.

**Comment by oberon2007** [comment]
great! one last question: **.moc/playlist.m3u** looks like your private play history... do you really want to include that?

**Comment by Chrysostomus** [comment]
Fixed now, also for bspwm profile

**Comment by oberon2007** [comment]
Everything needed for awesome should be available in unstable now :)

**Pull request merged**
