### PR TITLE
Lxde: add keybindings for tiling on edges and top-bottom halves with Super+Arrows

### PR DESCRIPTION
**Pull request by ThanosApostolou**
Tiling keybinds exist already for Super+Keypad 1-9 (which support tiling at corners too). However, many laptops don't have keypad at all. So, I also added tiling on left,right,top,bottom edges with Super+Arrows.

### CODE REVIEW

**Comment by ThanosApostolou** [comment]
I also added keybindings for windows screenshot (Alt+Print) and select-area screenshot (Shift+Print)

**Comment by ThanosApostolou** [comment]
I also fixed lxde session not starting when X is launched with **startx** instead of **lightdm** (see problem here: https://forum.manjaro.org/t/startx-start-with-pcmanfm-instead-lxde/25368)

**Comment by Ste74** [comment]
Why put here start lxde ? Don't work for you this shared command without override in your lxde profiles?

https://github.com/manjaro/desktop-settings/blob/master/shared/skel/.xinitrc#L59

i don't know lxde :\

**Comment by ThanosApostolou** [comment]
Yeah it works fine, that's why I removed the line **exec startlxde** from the **.extend.xinitrc** in the last commit.

It was actually the **dbus-launch pcmanfm** line which was causing the problem. This line existed in the old lxde profile, from the previous lxde maintainer. I don't if it served any purpose then, but it now only causes problems.

**Comment by Ste74** [comment]
So why don't remove the .extended* files and create a symlink from our shared folder for files like other profiles ?

**Comment by ThanosApostolou** [comment]
Sorry, I could be wrong, but I don't see any symlinks in the other profiles. For example mate, kde, cinnamon:
https://github.com/manjaro/desktop-settings/blob/master/community/mate/skel/.extend.xinitrc
https://github.com/manjaro/manjaro-kde-settings/blob/master/etc/skel/.extend.xinitrc
https://github.com/manjaro/desktop-settings/blob/master/community/cinnamon/skel/.extend.xinitrc

**Comment by ThanosApostolou** [comment]
If I understand this correctly, then if I remove the **.extend.xinitrc** then the default session is **xfce4-session** (I just tested it on lxde and I get an error when I **startx** that xfce4-session is not found). The **.extend.xinitrc** is there just so that it selects the **startlxde** instead of **xfce4-session**, similar to the rest editions.

**Comment by oberon2007** [comment]
**startx** takes an argument via .xinitrc.
`startx ~/.xinitrc session`
Normally the DM should take care of that. Not sure why apparently this isn't working in your case. Maybe your lightdm isn't configured correctly?

**Comment by ThanosApostolou** [comment]
No, lightdm works fine. It's just that a user wants to completely remove lightdm (most likely for minimizing RAM usage). I see that all the other editions are selecting the **DEFAULT_SESSION** in the **extend.xinitrc** file, so that's why I've kept the original file from the old lxde release. The only thing I've changed is removing a line **dbus-launch pcmanfm**, which was included by the previous maintainer and it seems that it's causing problems.

**Comment by oberon2007** [comment]
I see. You can of course keep the **.extend.xinitrc** but the standard .xinitrc should work aswell with lightdm, which it does, I gather.
The user would just need to use startx in the proper way with the arguments as I just mentioned or edit his **.xinitrc** like shown in the [Archwiki](https://wiki.archlinux.org/index.php/Xinit) 😄

**Comment by ThanosApostolou** [comment]
Nice, now I understood completely how this works 😃 

Since, all the other editions include the **.extend.xinitrc** file though, I believe it's better to keep it as well, so that the **startx** command defaults in lxde session.

**Pull request merged**
