### PR TITLE
Better Openbox Fonts Settings

### PR DESCRIPTION
**Pull request by robsonsilv4**
Decrease Size for a Better Look

### CODE REVIEW

**Comment by ThanosApostolou** [comment]
I kinda like it on the size they are now (12 and 10). Is it any specific problem or any specific reason why you want it on lower size (10 and 9)?

**Comment by oberon2007** [comment]
The 'right' font size totally depends on the screen size/resolution you are using. So it's not really possible to make a decision that will be good for everyone.
What I see as the default in most places is 10px (which of course will be too small on large screens) ... 😉

**Comment by ThanosApostolou** [comment]
@oberon2007 Ok in order to make everybody happy, can you modify it at size **11** and **10** as a middle solution and then merge it?

**Comment by oberon2007** [comment]
so, is this happening? 😉

**Comment by ThanosApostolou** [comment]
Aaaa I had forgot about. I believe it's better to leave it as it is, after all. I've also increased the lxpanel. I like things to be big! :stuck_out_tongue:

**Comment by oberon2007** [comment]
Ok,
# FINE!
😆

**Pull request closed without merging**
