### PR TITLE
Update bpswm profile

### PR DESCRIPTION
**Pull request by Chrysostomus**

### CODE REVIEW

**Comment by oberon2007** [comment]
@Chrysostomus please have a look at **skel/.config/spacefm/session** and **spacefm/session-last** ! There are some private paths in those settings ... :wink:

**Comment by Chrysostomus** [comment]
Thanks, I'll take a look.

**Comment by Chrysostomus** [comment]
Gonna be a pain in the ass to fix this...

**Comment by oberon2007** [comment]
So sorry ... :stuck_out_tongue_closed_eyes:

**Comment by Chrysostomus** [comment]
Fixed. Sed is a beautiful thing...

**Comment by Chrysostomus** [comment]
Thanks!
Can you rebuild desktop-settings-bspwm package?

**Comment by oberon2007** [comment]
did that immediately after merge! :smiley:

**Comment by Chrysostomus** [comment]
Thanks :)

**Pull request merged**
