### PR TITLE
Creating from scratch a Manjaro LXDE community edition

### PR DESCRIPTION
**Pull request by ThanosApostolou**
I want to create and maintain a new LXDE edition. I have made the relevant post here: https://forum.manjaro.org/t/i-would-like-to-adopt-and-maintain-the-manjaro-lxde-edition/20662?u=thanos_apostolou.

I'm trying to make it as "official" as possible, so I want to change the manjaro-lxde-settings package with my modifications (it is outdated anyway so I don't think it will matter anyone). I deleted all the old files except those that I find useful and uploaded mine.

If you accept this request, then I will continue and do a pull request here: https://github.com/manjaro/packages-community/tree/master/desktop-settings in order to add some dependencies for manjaro-lxde-settings (like qt5ct). 

Final step will be to add a lxde iso-profile under here: https://github.com/manjaro/iso-profiles/tree/master/community

If I need to do anything more please guide me because I'm totally new to this.

### CODE REVIEW

**Comment by oberon2007** [comment]
Thank you! I'll be happy to review this in a few days :+:

**Comment by oberon2007** [comment]
It would be great if you could share your profile, too, then we can just build your ISO to cheek it out... 😉

**Comment by ThanosApostolou** [comment]
@oberon2007 I uploaded the files I use here: https://github.com/ThanosApostolou/iso-profiles/tree/master/community/lxde

I didn't include the /etc/skel files under desktop-overlay since I want them to get installed from manjaro-lxde-settings package.

Also if you approve this pull request's changes, I will remove from the Packages-Desktop these lines:
```
## manjaro-lxde-settings
manjaro-base-skel
arc-maia-icon-theme
vertex-maia-themes
breath-wallpaper
qt5ct
qt5-styleplugins
```
and I will do a pull request to add those packages as dependencies for manjaro-lxde-settings. If I have understood correctly by watching yours and Stefano's builds, that's the correct way to do it. If not please tell me what to do.

I don't do any pull request for my lxde folder at iso-profiles yet because I cannot build ISOs anymore since the last updates (I get errors even when building the official profiles) so I cannot test the latest changes that I have made.

**Comment by Ste74** [comment]
You can build the iso without the desktop-settings temporary .. only move the desktop-settings in the right overlay folder in your iso-profiles .. btw i see your comment on the forum , mt have big changes for the grub menù entry and other think you have to use the profiles into our repo ( boxit ) and not the git profiles ...

**Comment by ThanosApostolou** [comment]
@Ste74 Yeah my test builds in my computer are done by including the skel files manually in the `desktop-overlay/etc` folder. However, it would be nice to be done automatically by using the `manjaro-lxde-settings` package and maybe that way the edition will be ready fast enough for the 17.0.1 release. :)

Today I can build without problems using the manjaro-tools-git and the iso-profiles from git. I did a pull request to include my lxde profile files in the manjaro/iso-profiles. I will try later this day to build using the tools from the unstable repositories as I think that they are working properly now.

**Comment by ThanosApostolou** [comment]
I believe my release is more or less ready! I know that you are really busy this period of time, but I would be really happy if you accepted this pull request and tell me what to do next in order to get the changes to the `manjaro-lxde-settings` package in order to include it in my edition, as soon as you can. :) If I need more steps in order to get this edition accepted as Community Edition please tell me. At this point I'm uploading the ISOs no my personal sourceforge account, so if you officially accept my edition I need guidance to tell me how I can upload the images officially to the manjaro's sourceforge page

**Comment by oberon2007** [comment]
I'm quite happy with what I've seen sofar and also with your response to some first feedback 👍 Will download your ISO and try it tomorrow.

**Comment by ThanosApostolou** [comment]
@oberon2007  Thank you! I'm building now an ISO with all the latest changes and I will upload it right afterwards.  I will provide my download link to the forum post.

**Comment by philmmanjaro** [comment]
OK, so your files can be found on [sourceforge](https://sourceforge.net/projects/thanos-manjaro-lxde/files/).

**Comment by oberon2007** [comment]
You've defined Breeze cursor for lightdm-gtk-greeter but not for the desktop. Not sure what will be needed for lxde... I see a setting in **.config/lxsession/LXDE/desktop.conf**, maybe it's sufficient to set it there. Other possible places would be **.config/gtk-3.0/settings.ini**, **~/.gtkrc-2.0** and/or **~/.icons/default/index.theme**. Some environments also need **/usr/share/icons/default/index.theme** for the setting to work everywhere - you probably need to play around a little to find out what is needed. Of course to set it at user level will be better and if possible in just one place... even better 😉 
Apart from that I have no objections.
For my taste the font size is a bit big - well, I have a small screen... 😆 I think all our other editions use 10px or 11px.
It's a bit strange btw that both lxappearance and that other lxde desktop settings tool provide font settings and they seem to ignore each other ...? 😆
All in all I am happy to merge both your PRs. Thank you for the contribution, great job!

**Comment by ThanosApostolou** [comment]
Thanks a lot @oberon2007 . I will set Adwaita cursor theme to lightdm-gtk-greeter too because I don't really like the feeling of breeze cursor on lxde. The lxde tools are indeed a bit weird on how they work but I'm trying to figure them out. Just to be clear (because I don't have much experience on git and github), after you merge the PR, whenever I want to change something I will have to refork this repository and do a new pull request right?

**Comment by oberon2007** [comment]
No need to re-fork it. You can either simply create pull requests in the other direction and merge them to update your fork with upstream changes (probably best if that's still new for you...) or, the totally pro way would be to create a remote 'upstream tracking branch' 😉 
```
git remote add upstream https://github.com/manjaro/desktop-settings.git
git fetch upstream
git checkout -b manjaro-master upstream/master
```
then later when you want to fetch upstream changes to your tracking branch:
```
git fetch upstream
git checkout manjaro-master
git merge upstream/master
```
and to merge upstream to your local fork:
```
git checkout master
git merge manjaro-master
```
In the long run @philmmanjaro might just grant you push access to the manjaro repo... 😉

**Pull request merged**
