### PR TITLE
upgrade 16.06.1

### PR DESCRIPTION
**Pull request by holmeslinux**
upgrade Edition JWM 16.06.1

### CODE REVIEW

**Comment by Ste74** [comment]
@holmeslinux check the conflict :smile:

**Comment by holmeslinux** [comment]
@Ste74 
kkkkkkkkkk
conflict? where you see it?

**Comment by Ste74** [comment]
you have two file in conflict : 
.conkyrc have conflict at the end 
```
 <<<<<<< HEAD
${alignr}${color2}${font Cantarell:size=9}uptime ${color}${uptime_short}
${alignr}${color2}${font Cantarell:size=9}${alignr}kernel ${color}${kernel}
${alignr}${color2}${font Cantarell:size=9}${alignr}architecture ${color}${machine} Systemd
${voffset 10}${alignr}${color} updates currently available ${color ffffff}${font Cantarell:bold:size=10}${execpi 10800 checkupdates | wc -l}${font}${color}
=======
${alignr}${color2}${font Cantarell:size=9}uptime ${uptime_short}
${alignr}${color2}${font Cantarell:size=9}${alignr}kernel ${kernel}
${alignr}${color2}${font Cantarell:size=9}${alignr}architecture ${machine} Systemd
${voffset 10}${alignr} updates currently available ${color ffffff}${font Cantarell:bold:size=10}${execpi 10800 checkupdates | wc -l}${font}${color}
>>>>>>> 10bd2fbb110912b7ab9dfc4e98c0df7dda1a0491
]]

```
and .config/libfm/libfm.conf
```
<<<<<<< HEAD
=======
places_trash=1
>>>>>>> 10bd2fbb110912b7ab9dfc4e98c0df7dda1a0491
places_unmounted=1
```

check it

**Comment by holmeslinux** [comment]
ok, @Ste74 
already made changes and i need to do now?
request a new pull?

**Comment by Ste74** [comment]
No not needed , github refresh automatically your pull :wink:

**Pull request closed without merging**
