### PR TITLE
properly fix desktop-items for gtk3-based DEs:

### PR DESCRIPTION
**Pull request by oberon2007**
In order for the .desktop files to be recognized as launchers in the running Deepin session they need to be executable already when they are created on the Desktop.
When we create them and chmod only afterwards the items are treated as text files until relogging (native name displayed and opened with texteditor when double-clicked instead of launching the applications).

Deleted line 13. was it a mistake?

### CODE REVIEW

**Comment by udeved** [comment]
I would reject this pull request, because it removes the executable bit.
I don't like this change per se, because we don't know if it negatively effects official profiles first, and others too.

**Comment by oberon2007** [comment]
What do you mean with "executable bit"?
I notice that some apps deliver their .desktop files executable, others not executable. So it is not likely that executable .desktop files do any harm anywhere, is it?

**Comment by oberon2007** [comment]
I mean, what do you mean with "remove executable bit"? The script adds it, doesn't it ? ;)

**Comment by udeved** [comment]
The script add executable bit +x after copy.
I reject that launchers in /usr/share/applications get executable bit just to satify a still in development deepin.

**Comment by oberon2007** [comment]
Hm. There doesn't seem to be a convention about launchers being executable or not
executable
As you see, some are, some are not.
We know that having them executable benefits deepin (others maybe, too). We do not know of any harm it does on the other hand...
Anyway. You have to decide. My only way to workaround this will be to change the script in the chroot :stuck_out_tongue_closed_eyes:

**Comment by udeved** [comment]
Well, I will definitely reject manipulating launchers in /usr/share, some other DEs may not like this executable bit.

**Comment by udeved** [comment]
It comes down to deploying package fixes on iso, which was just eliminated, since its bad practice.
question is, is it a deepin issue, or shold the packages install executable launchers.
Should not be addressed by manipulating the launcher on iso in the install location.

**Comment by philmmanjaro** [comment]
Just a comment from my end: We already made those .desktop files executable. However you modified the source file. Always modify the target file, so these changes were not needed at all ...

**Comment by oberon2007** [comment]
I think there is a bit of a misunderstanding now, @philmmanjaro 
I understand that it would be bad practice to chmod the source.
But let me describe the problem again:
Copying the .desktop files to ~/Desktop while they are still non-executable leaves them un-usable as launchers in Deepin until you re-log, even when you make them exectuable after copy - seems to be an oddity of Deepin, (I don't know about Cinnamon and others, yet) and I guess that's the reason why all native deepin-applications come with executable launcher files.
In any case, to be able to deliver usable launchers in Deepin they have to be executable already when they appear on the desktop.
How about copying the originals to **~/.local/share/applications** first, then chmod them there and move them to the desktop afterwards.
On a side note: the launcher for the CLI-installer in /usr/share/applications is already executable! If that is not desired it should be changed - or from my perspective I'd prefer to ship Thus and Calamares with executable launchers, too ;) :laughing:

**Comment by philmmanjaro** [comment]
All packages added to **Desktop** need to be executable, else they won't work on any DE. So we have to see which routine is doing that and fix it there.

**Pull request closed without merging**
