### PR TITLE
add configure palemoon

### PR DESCRIPTION
**Pull request by holmeslinux**
special configuration to palemoon

vlw fwi, Holmes :)

### CODE REVIEW

**Comment by holmeslinux** [comment]
hello oberon,
i saw that some files were removed from .moonchild productions/pale moon/.
to avoid duplication of i removed the file manjaro-browser-settings of the Package-Jwm.
You can leave as i have sent?

vlw fwi, Holmes :)

**Comment by oberon2007** [comment]
Hi Holmes! The result for palemoon should be the same with using the browser settings package and your additional bookmarks like this. I have tried it here :-) advantage with browser settings package is that it installs manjaro bookmarks also for other browsers and it can be updated later, too. 
Any customization you are missing you think?

**Comment by oberon2007** [comment]
The jwm bookmarks are still there!

**Comment by holmeslinux** [comment]
i made other small changes in layout.

**Pull request merged**
